spring:
    application:
        name: ms_calculator_tenpo
    datasource:
        url: jdbc:postgresql://${MSCALC_DB_HOST}:${MSCALC_DB_PORT}/${MSCALC_DB_NAME}
        username: ${MSCALC_DB_USER}
        password: ${MSCALC_DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
server:
    port: 8080
    servlet:
        context-path: /api/${MSCALC_API_VERSION}
    error:
        include-stacktrace: never
        include-binding-errors: never
        include-exception: false
external:
    percentage-service:
        base-url: ${MSCALC_WEBSERVICE_PERCENTAGE}
        endpoints:
            get-percentage: /${MSCALC_API_VERSION}/percentage
            health: /${MSCALC_API_VERSION}/actuator/health
        timeout: 5s
cache:
    percentage-service:
        ttl: ${MSCALC_API_CACHE_TTL}
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui
    default-produces-media-type: application/json
docs-info:
    app:
        title: Tenpo Calculator Backend Service
        description: Backend Challenge! Desarrollado por Sebastián Kravetz para TENPO Chile.
        version: 1.0.0
