spring:
  application:
    name: ms_percentage_tenpo
server:
  port: 8081
  servlet:
    context-path: /api/v1
  error:
    include-stacktrace: never
    include-binding-errors: never
    include-exception: false
